version: "3.8"

services: 
  backend:
    build:
      context: ./backend
    container_name: cinema_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=cinema
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - MAIL_MAILER=smtp
      - MAIL_HOST=mailpit
      - MAIL_PORT=1025
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "php artisan migrate --force && php artisan app:sincronizar-peliculas && php artisan serve --host=0.0.0.0 --port=8000"
    networks:
      - cinema_network

  frontend:
    build:
      context: ./frontend
    container_name: cinema_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Prevent overwriting node_modules with host folder
    depends_on:
      - backend
    networks:
      - cinema_network

  realtime:
    build:
      context: ./realtime
    container_name: cinema_realtime
    ports:
      - "3002:3002"
    volumes:
      - ./realtime:/app
      - /app/node_modules # Prevent overwriting node_modules with host folder
    networks:
      - cinema_network

  db:
    image: mysql:8.0
    container_name: cinema_db
    restart: always
    environment:
      MYSQL_DATABASE: cinema
      MYSQL_ROOT_PASSWORD: root
    ports:   
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - cinema_network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: cinema_adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - cinema_network
    depends_on:
      - db

  mailpit:
    image: axllent/mailpit
    container_name: cinema_mailpit
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - cinema_network

networks:
  cinema_network:
    driver: bridge

volumes:
  db_data:
